name: influxdb-lukewh
version: '1.8'
summary: InfluxDB
description: |
  InfluxDB

base: core18
confinement: strict
grade: stable

parts:
  influxdb:
    plugin: python
    source: https://github.com/influxdata/influxdb.git
    source-tag: v1.8.0
    build-snaps:
      - go
    override-build: |
      python3 build.py --outdir $SNAPCRAFT_PART_INSTALL/bin

apps:
  influxd:
    command: bin/influxd
    daemon: simple
    plugs:
      - network
      - network-bind
  influx:
    command: bin/influx
    plugs:
      - network
